apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: venkatexh/th-auth
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: venkatexh/th-client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: venkatexh/th-tickets
    context: tickets
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: venkatexh/th-orders
    context: orders
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: venkatexh/th-expiration
    context: expiration
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: venkatexh/th-payments
    context: payments
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: true
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}